AB#85 move from buefy to vuetify
RenaissanceTeam/tygojira_web pull request #3
Opened 2020-02-04 17:21 UTC by b1nd

2020-02-05 08:16 UTC, ZheMadScientist commented on src/router.js
> -      component: () => import('./view/About.vue'),
это была lazy инициализация, но да ладно

2020-02-05 08:16 UTC, makarfrfr approved these changes

2020-02-05 08:23 UTC, b1nd commented on src/router.js
> -      component: () => import('./view/About.vue'),
А что звучит функциональненько, верну

2020-02-05 15:07 UTC, makarfrfr requested changes
Изменить url сервера для прод мода

2020-02-06 17:45 UTC, makarfrfr approved these changes

2020-02-06 19:13 UTC, merged